syntax on

set nobk
set tabstop=4
set noexpandtab
set cindent
set shiftwidth=4
set number

set hlsearch

let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
let Tlist_Use_Right_Window=1

set nocp
filetype plugin on

let g:SuperTabDefaultCompletionType="context"

